import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import PathnameWrapper from 'components/Pathcomponent/PathnameWrapper'
import PrelineScript from 'components/PrelineScript'

import "./globals.css";

const montserrat  = Montserrat(
  { subsets: ["latin"],
    variable: "--font-montserrat",

  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}><PathnameWrapper> {children} 
        
      <PrelineScript />
      </PathnameWrapper></body>
    </html>
  );
}
